url_after_course = ['AgACAgIAAxkBAAIJHmUUrLYBV6d6oQrA9VZZNJYdHyYQAAKX2TEbfOGhSGs1ooisydkjAQADAgADeQADMAQ',
                    'AgACAgIAAxkBAAIJNWUUrOZeaTAH544p1KHODEmbbfXwAAKn2TEbfOGhSMcY_N1WgznKAQADAgADeQADMAQ',
                    'AgACAgIAAxkBAAIJNmUUrObR51H7qJD_Cw-kQD3bBqhkAAKo2TEbfOGhSCUHxhgP7j97AQADAgADeQADMAQ',
                    'AgACAgIAAxkBAAIJN2UUrOalbDazpXl-tRjRex0MMeK-AAKp2TEbfOGhSBNwOZuxmHmWAQADAgADeQADMAQ']
url_hello = ['AgACAgIAAxkBAAIKdWUa4WmZHs04tROOUYEStZYFRNvZAAIlzTEb8KfZSM39rTbnWIZzAQADAgADeQADMAQ',
             'AgACAgIAAxkBAAIKdmUa4Wng8Qus5X045qYGeEmrFeciAAInzTEb8KfZSEQJHRmxZVFqAQADAgADeQADMAQ',
             'AgACAgIAAxkBAAILz2Ub0Vtx7fhhn8R_5Xh0Ei8NzHp8AAK52DEb5PjYSB0m6YwCIuJNAQADAgADeQADMAQ']

url_video_class = ['AgACAgIAAxkBAAIKtWUa-yLjOpar5TZ6KJ10z_cgUt9OAAI10TEbYbzYSCBVHbQznU9_AQADAgADeQADMAQ',
                   'AgACAgIAAxkBAAIKtmUa-yJQcdrfZ4kPYrSWHXgdrvOcAALPzTEb8KfZSHqXb2Lf-HwPAQADAgADeQADMAQ',
                   'AgACAgIAAxkBAAIKt2Ua-yLj_YvxDJ6D5grSFYjIrYN2AALQzTEb8KfZSAfzkEAorlpJAQADAgADeQADMAQ',
                   'AgACAgIAAxkBAAIKuGUa-yLRFI5JwfQ8TSyKitToKGcDAALRzTEb8KfZSEc21GoRpHsUAQADAgADeQADMAQ',
                   'AgACAgIAAxkBAAIKuWUa-yKJioX9lQa-U8ul9k1ZPC0eAALSzTEb8KfZSPYBnVpnIGPEAQADAgADeQADMAQ',
                   'AgACAgIAAxkBAAIKumUa-yIroDNTbdoCm0AdU1iGYL8dAALTzTEb8KfZSF2B8F3peVxWAQADAgADeQADMAQ']
url_intro_exercise = ['AgACAgIAAxkBAAILz2Ub0Vtx7fhhn8R_5Xh0Ei8NzHp8AAK52DEb5PjYSB0m6YwCIuJNAQADAgADeQADMAQ',
                      'AgACAgIAAxkBAAIL0GUb0Vt33teoRDPXTb-AwgABjV7ZDwACu9gxG-T42EhmTy8RfqkDmgEAAwIAA3kAAzAE',
                      'AgACAgIAAxkBAAIL0WUb0VtHUzc0cwOSLPK03TDoF8bEAAKy2DEb5PjYSKOasvhCwQWKAQADAgADeQADMAQ',
                      'AgACAgIAAxkBAAIL0mUb0VsXa25YSOiqJywp7GRyn1i5AAKz2DEb5PjYSO1zVLiPysFJAQADAgADeQADMAQ',
                      'AgACAgIAAxkBAAIL02Ub0Vv4JVs11VAepAdykvnI0Of7AAK02DEb5PjYSKu5x0053RSDAQADAgADeQADMAQ',
                      'AgACAgIAAxkBAAIL1GUb0VuwNKjNK9iTgO5OTHqB2UWgAAK12DEb5PjYSL1q7hW5auKXAQADAgADeQADMAQ',
                      'AgACAgIAAxkBAAIL1WUb0VuwoOuaAAEkX7EXytHWTrG_ZgACttgxG-T42EgfzFsypBcW6QEAAwIAA3kAAzAE',
                      'AgACAgIAAxkBAAIL1mUb0Vv1HkXYEgaplBkyNe0VEfKgAAK32DEb5PjYSBuIdZxsx5kmAQADAgADeQADMAQ']
url_about_tracker = ['AgACAgIAAxkBAAIMRGUb2Pmjxb0614UsISa59DcdIc3xAAKw0DEb1ffgSLli7ZGnfKmtAQADAgADeQADMAQ',
                     'AgACAgIAAxkBAAIMUGUb2R_3rvIGl42KO8hLuTD1K5NIAAK00DEb1ffgSPaROndRHhfcAQADAgADeQADMAQ',
                     'AgACAgIAAxkBAAIMRmUb2PlID50EYgaYtM4xdk_wtVi9AAKy0DEb1ffgSPXr7-hA_GSEAQADAgADeQADMAQ',
                     'AgACAgIAAxkBAAIMR2Ub2PncFVj8ftOenuZKBRVDKuA3AAKz0DEb1ffgSKrLw_089YcCAQADAgADeQADMAQ',
                     'AgACAgIAAxkBAAIL6WUb0a_yT9BDbB_KB9ncV7eBT0GqAAJczzEb1ffgSIr_pcFN3aWoAQADAgADeQADMAQ']
