"""last8

Revision ID: 001722091176
Revises: b29f199755af
Create Date: 2023-09-24 13:48:20.148620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001722091176'
down_revision: Union[str, None] = 'b29f199755af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], name='pictures_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictures_pkey')
    )
    # ### end Alembic commands ###
