"""last3

Revision ID: 15376d1e4220
Revises: 8765d182eea8
Create Date: 2023-09-24 13:04:41.581959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15376d1e4220'
down_revision: Union[str, None] = '8765d182eea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pictures')
    op.drop_table('content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('content_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='content_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('pictures',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='pictures_content_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pictures_pkey')
    )
    # ### end Alembic commands ###
