"""last12

Revision ID: 52d044a805ae
Revises: e659ac89d02b
Create Date: 2023-09-25 16:50:21.088980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d044a805ae'
down_revision: Union[str, None] = 'e659ac89d02b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('next_post_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('prev_post_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'prev_post_id')
    op.drop_column('posts', 'next_post_id')
    # ### end Alembic commands ###
