"""last39

Revision ID: 700a9a47f8b0
Revises: bc8bd2b93914
Create Date: 2023-10-10 19:19:51.828394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700a9a47f8b0'
down_revision: Union[str, None] = 'bc8bd2b93914'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('section_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_logs', 'section_id')
    # ### end Alembic commands ###
