"""last38

Revision ID: bc8bd2b93914
Revises: d1e5da434da1
Create Date: 2023-10-10 16:42:41.884037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc8bd2b93914'
down_revision: Union[str, None] = 'd1e5da434da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('learning_section', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'learning_sections', ['learning_section'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'learning_section')
    # ### end Alembic commands ###
