"""last35

Revision ID: d527b2a7b600
Revises: 0a6ef5731e52
Create Date: 2023-10-07 08:05:21.639891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd527b2a7b600'
down_revision: Union[str, None] = '0a6ef5731e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('date_get_exercise', sa.DateTime(), nullable=True))
    op.add_column('exercise_logs', sa.Column('date_change_status', sa.DateTime(), nullable=True))
    op.drop_column('exercise_logs', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('exercise_logs', 'date_change_status')
    op.drop_column('exercise_logs', 'date_get_exercise')
    # ### end Alembic commands ###
