"""last17

Revision ID: 103c5ba9d5f6
Revises: c4f84d304cd7
Create Date: 2023-09-27 19:49:36.735488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '103c5ba9d5f6'
down_revision: Union[str, None] = 'c4f84d304cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
