"""last32

Revision ID: 1863e5d030b0
Revises: af68871f185e
Create Date: 2023-10-01 18:42:44.162211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1863e5d030b0'
down_revision: Union[str, None] = 'af68871f185e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_logs_user_id_fkey', 'exercise_logs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('exercise_logs_user_id_fkey', 'exercise_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
