"""last14

Revision ID: 2946b0ec05e1
Revises: 86c6644c7847
Create Date: 2023-09-25 19:39:57.945969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2946b0ec05e1'
down_revision: Union[str, None] = '86c6644c7847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'posts', ['last_post_id'], ['id'])
    op.drop_column('users', 'id_last_post')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_last_post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'last_post_id')
    # ### end Alembic commands ###
