"""last15

Revision ID: 464a1eb88a8a
Revises: 2946b0ec05e1
Create Date: 2023-09-25 22:51:03.115598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '464a1eb88a8a'
down_revision: Union[str, None] = '2946b0ec05e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('next_post_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_last_post_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'posts', ['next_post_id'], ['id'])
    op.drop_column('users', 'last_post_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_last_post_id_fkey', 'users', 'posts', ['last_post_id'], ['id'])
    op.drop_column('users', 'next_post_id')
    # ### end Alembic commands ###
