"""last19

Revision ID: 49bc15fc621b
Revises: 17f22c3e1949
Create Date: 2023-09-27 19:55:23.626910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49bc15fc621b'
down_revision: Union[str, None] = '17f22c3e1949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feelings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeling_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('feeling_id', sa.Integer(), nullable=True),
    sa.Column('feeling_str', sa.String(), nullable=True),
    sa.Column('describe', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['feeling_id'], ['feelings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeling_logs')
    op.drop_table('feelings')
    # ### end Alembic commands ###
