"""last33

Revision ID: 8036aa221f1c
Revises: 1863e5d030b0
Create Date: 2023-10-04 11:33:52.383199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8036aa221f1c'
down_revision: Union[str, None] = '1863e5d030b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise_logs', 'date')
    # ### end Alembic commands ###
