"""last30

Revision ID: bc1d9c3bb1e2
Revises: eac61c8b98e9
Create Date: 2023-10-01 15:52:42.461178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1d9c3bb1e2'
down_revision: Union[str, None] = 'eac61c8b98e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_exercise', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_exercise')
    # ### end Alembic commands ###
